[package]
name = "openexr-core-sys"
version = "0.1.0"
edition = "2018"
build = "build.rs"

[lib]
name = "openexr_core_sys"
path = "src/lib.rs"

[dependencies]
thiserror = "1.0.35"

[build-dependencies]
bindgen = "0.60.1"
anyhow = "1.0.65"
