[project]
name = "exr-func-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pydantic>=2.10.3"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
