[package]
name = "openexr-core"
version = "0.1.0"
edition = "2018"

[dependencies]
openexr-core-sys = { path = "../openexr-core-sys" }
anyhow = "1.0.65"
cfg-if = "1.0.0"
cgmath = { version = "0.18.0", optional = true }
nalgebra-glm = { version = "0.17.0", optional = true }
thiserror = "1.0.35"
